name: Python application test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev --deploy
        working-directory: backend
      - name: Run pytest
        run: |
          pipenv run pytest
        working-directory: backend
